# argocd/projects/app-of-apps-project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps-project
  namespace: argocd
spec:
  description: Project for root App of Apps – highest privilege
  sourceRepos:
    - https://github.com/sabermaraghi/bash-mastery-devops.git
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
