FROM alpine:latest
RUN apk add --no-cache curl
COPY entrypoint.sh /app/entrypoint.sh
COPY healthcheck.sh /app/healthcheck.sh
RUN chmod +x /app/*.sh
HEALTHCHECK --interval=30s --timeout=3s CMD /app/healthcheck.sh

