apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-environments
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev      ; overlay: dev      ; namespace: microservices-dev      ; project: microservices-project
          - env: staging  ; overlay: staging  ; namespace: microservices-staging  ; project: microservices-project
          - env: prod     ; overlay: prod     ; namespace: microservices-prod     ; project: default
  template:
    metadata:
      name: 'microservices-{{env}}'
    spec:
      project: '{{project}}'
      source:
        repoURL: https://github.com/sabermaraghi/bash-mastery-devops.git
        targetRevision: main
        path: argocd/overlays/{{overlay}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
