apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-environments
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev       ; path: argocd/overlays/dev       ; ns: microservices-dev
          - env: staging   ; path: argocd/overlays/staging   ; ns: microservices-staging
          - env: prod      ; path: charts/microservices      ; ns: microservices-prod ; values: values-prod.yaml
  template:
    metadata:
      name: 'microservices-{{env}}'
    spec:
      project: microservices-project
      source:
        repoURL: https://github.com/sabermaraghi/bash-mastery-devops.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - '{{values}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ns}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
