# argocd/applications/root-app-of-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: app-of-apps-project
  source:
    repoURL: https://github.com/sabermaraghi/bash-mastery-devops.git
    targetRevision: main
    path: argocd/applications
    directory:
      exclude: "root-app-of-apps.yaml,bootstrap-root.yaml" 
      include: "{dev,staging,prod}.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
